<!-- Generated by Trae Work -->
<script setup lang="ts">
import { ref, computed } from 'vue'

export interface SkillInfo {
  id: string
  name: string
  icon: string
  description: string
  active: boolean
}

export interface AgentVariant {
  id: string
  name: string
  description: string
  icon?: string
}

const props = defineProps<{
  agentName: string
  agentDescription: string
  agentIcon: string
  variantId: string
  variantName: string
  variants?: AgentVariant[]
  skills: SkillInfo[]
  temperature?: number
  maxTokens?: number
}>()

const emit = defineEmits<{
  (e: 'variant-change', variantId: string): void
  (e: 'skill-toggle', skillId: string): void
}>()

const showVariantPicker = ref(false)

const activeSkillCount = computed(() =>
  props.skills.filter(s => s.active).length
)

const currentVariant = computed(() =>
  props.variants?.find(v => v.id === props.variantId)
)

function toggleVariantPicker() {
  showVariantPicker.value = !showVariantPicker.value
}

function selectVariant(variantId: string) {
  emit('variant-change', variantId)
  showVariantPicker.value = false
}

function handleSkillToggle(skillId: string) {
  emit('skill-toggle', skillId)
}
</script>

<template>
  <div class="agent-card">
    <!-- Agent 头部 -->
    <div class="agent-header">
      <div class="agent-avatar">
        <span class="avatar-icon">{{ agentIcon }}</span>
        <div class="avatar-ring"></div>
      </div>
      <div class="agent-info">
        <div class="agent-name">{{ agentName }}</div>
        <div class="agent-desc">{{ agentDescription }}</div>
      </div>
      <div class="agent-status">
        <span class="status-dot"></span>
        <span class="status-text">运行中</span>
      </div>
    </div>

    <!-- 变体选择 -->
    <div class="variant-section">
      <div class="section-label">
        <span>🎭 风格变体</span>
        <span v-if="variants && variants.length > 1" class="variant-hint">点击切换</span>
        <span v-else class="variant-current">{{ variantName }}</span>
      </div>
      <div
        class="variant-pill"
        :class="{ 'is-open': showVariantPicker }"
        @click="variants && variants.length > 1 && toggleVariantPicker()"
      >
        <span class="pill-icon">✨</span>
        <span>{{ variantName }}</span>
        <span v-if="variants && variants.length > 1" class="pill-arrow">▾</span>
      </div>

      <!-- 变体下拉列表 -->
      <transition name="variant-dropdown">
        <div v-if="showVariantPicker && variants && variants.length > 1" class="variant-list">
          <div
            v-for="v in variants"
            :key="v.id"
            class="variant-option"
            :class="{ active: v.id === variantId }"
            @click.stop="selectVariant(v.id)"
          >
            <span class="option-icon">{{ v.icon || '✨' }}</span>
            <div class="option-info">
              <span class="option-name">{{ v.name }}</span>
              <span class="option-desc">{{ v.description }}</span>
            </div>
            <span v-if="v.id === variantId" class="option-check">✓</span>
          </div>
        </div>
      </transition>
    </div>

    <!-- 技能组合 -->
    <div class="skills-section">
      <div class="section-label">
        <span>🔧 技能组合</span>
        <span class="skills-count">{{ activeSkillCount }}/{{ skills.length }} 激活</span>
      </div>
      <div class="skills-grid">
        <div
          v-for="skill in skills"
          :key="skill.id"
          class="skill-chip"
          :class="{ active: skill.active }"
          @click="handleSkillToggle(skill.id)"
          :title="skill.description"
        >
          <span class="skill-icon">{{ skill.icon }}</span>
          <span class="skill-name">{{ skill.name }}</span>
        </div>
      </div>
    </div>

    <!-- 参数指标 -->
    <div class="params-section">
      <div class="param-row">
        <span class="param-label">🌡️ 创造性</span>
        <div class="param-bar">
          <div
            class="param-fill"
            :style="{ width: (temperature ?? 80) / 200 * 100 + '%' }"
          ></div>
        </div>
        <span class="param-value">{{ temperature ?? 80 }}</span>
      </div>
    </div>
  </div>
</template>

<style scoped>
.agent-card {
  background: linear-gradient(145deg, #1e1b4b 0%, #312e81 100%);
  border: 1px solid rgba(139, 92, 246, 0.3);
  border-radius: 12px;
  padding: 14px;
  position: relative;
  overflow: hidden;
}

.agent-card::before {
  content: '';
  position: absolute;
  top: -50%;
  right: -30%;
  width: 200px;
  height: 200px;
  background: radial-gradient(circle, rgba(139, 92, 246, 0.15) 0%, transparent 70%);
  pointer-events: none;
}

/* Agent 头部 */
.agent-header {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 14px;
  position: relative;
}

.agent-avatar {
  position: relative;
  width: 44px;
  height: 44px;
  flex-shrink: 0;
}

.avatar-icon {
  width: 44px;
  height: 44px;
  background: linear-gradient(135deg, #6366f1, #8b5cf6);
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 22px;
  box-shadow: 0 4px 12px rgba(99, 102, 241, 0.3);
}

.avatar-ring {
  position: absolute;
  inset: -3px;
  border: 2px solid rgba(139, 92, 246, 0.4);
  border-radius: 14px;
  border-right-color: transparent;
  animation: ring-spin 3s linear infinite;
}

@keyframes ring-spin {
  to { transform: rotate(360deg); }
}

.agent-info {
  flex: 1;
  min-width: 0;
}

.agent-name {
  font-size: 14px;
  font-weight: 700;
  color: #e0e7ff;
}

.agent-desc {
  font-size: 11px;
  color: #a5b4fc;
  margin-top: 2px;
}

.agent-status {
  display: flex;
  align-items: center;
  gap: 5px;
  flex-shrink: 0;
}

.status-dot {
  width: 7px;
  height: 7px;
  background: #10b981;
  border-radius: 50%;
  box-shadow: 0 0 8px #10b981;
  animation: status-pulse 2s ease-in-out infinite;
}

@keyframes status-pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.5; }
}

.status-text {
  font-size: 10px;
  color: #10b981;
  font-weight: 500;
}

/* 区块通用 */
.section-label {
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-size: 11px;
  color: #c4b5fd;
  margin-bottom: 8px;
  font-weight: 500;
}

/* 变体区 */
.variant-section {
  margin-bottom: 12px;
  padding-bottom: 12px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.08);
}

.variant-current {
  font-size: 10px;
  color: #a5b4fc;
  font-weight: normal;
}

.variant-pill {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 5px 12px;
  background: rgba(255, 255, 255, 0.08);
  border: 1px solid rgba(255, 255, 255, 0.12);
  border-radius: 20px;
  font-size: 11px;
  color: #e0e7ff;
}

.pill-icon {
  font-size: 12px;
}

/* 技能区 */
.skills-section {
  margin-bottom: 12px;
}

.skills-count {
  font-size: 10px;
  color: #a5b4fc;
  font-weight: normal;
}

.skills-grid {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.skill-chip {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 4px 8px;
  background: rgba(255, 255, 255, 0.04);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 6px;
  font-size: 10px;
  color: #94a3b8;
  cursor: pointer;
  transition: all 0.2s ease;
}

.skill-chip:hover {
  background: rgba(255, 255, 255, 0.08);
}

.skill-chip.active {
  background: rgba(99, 102, 241, 0.2);
  border-color: rgba(99, 102, 241, 0.5);
  color: #c7d2fe;
}

.skill-icon {
  font-size: 11px;
}

/* 参数区 */
.params-section {
  padding-top: 10px;
  border-top: 1px solid rgba(255, 255, 255, 0.08);
}

.param-row {
  display: flex;
  align-items: center;
  gap: 10px;
}

.param-label {
  font-size: 11px;
  color: #c4b5fd;
  flex-shrink: 0;
  width: 60px;
}

.param-bar {
  flex: 1;
  height: 4px;
  background: rgba(255, 255, 255, 0.08);
  border-radius: 2px;
  overflow: hidden;
}

.param-fill {
  height: 100%;
  background: linear-gradient(90deg, #6366f1, #a855f7);
  border-radius: 2px;
  transition: width 0.3s ease;
}

.param-value {
  font-size: 11px;
  color: #a5b4fc;
  font-weight: 600;
  width: 28px;
  text-align: right;
  flex-shrink: 0;
}

/* 变体选择器增强 */
.variant-hint {
  font-size: 10px;
  color: #a5b4fc;
  font-weight: normal;
  opacity: 0.7;
}

.variant-pill {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 5px 12px;
  background: rgba(255, 255, 255, 0.08);
  border: 1px solid rgba(255, 255, 255, 0.12);
  border-radius: 20px;
  font-size: 11px;
  color: #e0e7ff;
  cursor: default;
  transition: all 0.2s ease;
}

.variant-pill:hover {
  background: rgba(255, 255, 255, 0.12);
}

.variant-pill.is-open {
  background: rgba(99, 102, 241, 0.2);
  border-color: rgba(99, 102, 241, 0.5);
}

.pill-arrow {
  font-size: 10px;
  color: #a5b4fc;
  transition: transform 0.3s ease;
}

.variant-pill.is-open .pill-arrow {
  transform: rotate(180deg);
}

/* 变体下拉列表 */
.variant-list {
  margin-top: 8px;
  background: rgba(15, 23, 42, 0.95);
  border: 1px solid rgba(99, 102, 241, 0.3);
  border-radius: 8px;
  overflow: hidden;
  backdrop-filter: blur(10px);
}

.variant-dropdown-enter-active,
.variant-dropdown-leave-active {
  transition: all 0.25s ease;
  max-height: 300px;
  opacity: 1;
  transform: translateY(0);
}

.variant-dropdown-enter-from,
.variant-dropdown-leave-to {
  max-height: 0;
  opacity: 0;
  transform: translateY(-5px);
  margin-top: 0;
}

.variant-option {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 8px 10px;
  cursor: pointer;
  transition: background 0.2s ease;
  border-bottom: 1px solid rgba(255, 255, 255, 0.04);
}

.variant-option:last-child {
  border-bottom: none;
}

.variant-option:hover {
  background: rgba(99, 102, 241, 0.1);
}

.variant-option.active {
  background: rgba(99, 102, 241, 0.15);
}

.option-icon {
  font-size: 16px;
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(255, 255, 255, 0.05);
  border-radius: 6px;
  flex-shrink: 0;
}

.option-info {
  flex: 1;
  min-width: 0;
}

.option-name {
  display: block;
  font-size: 11px;
  font-weight: 600;
  color: #e0e7ff;
}

.option-desc {
  display: block;
  font-size: 10px;
  color: #818cf8;
  margin-top: 1px;
}

.option-check {
  font-size: 12px;
  color: #60a5fa;
  font-weight: 700;
}
</style>
