<!-- Generated by Trae Work -->
<script setup lang="ts">
import { ref, computed } from 'vue'

export interface MemoryItem {
  id: string
  title: string
  type: string
  importance?: number
  updated_at?: string
  description?: string
  tags?: string[]
}

export interface MemoryLevel {
  level: string
  name: string
  subtitle: string
  icon: string
  color: string
  items: MemoryItem[]
  capacity: string
  retention: string
  expanded?: boolean
}

const props = defineProps<{
  levels: MemoryLevel[]
  activeLevel?: string
}>()

const emit = defineEmits<{
  (e: 'level-click', level: string): void
  (e: 'item-click', level: string, itemId: string): void
}>()

const selectedItemId = ref<string | null>(null)
const selectedLevel = ref<string | null>(null)

const selectedItem = computed(() => {
  if (!selectedItemId.value || !selectedLevel.value) return null
  const level = props.levels.find(l => l.level === selectedLevel.value)
  return level?.items.find(i => i.id === selectedItemId.value) || null
})

function handleLevelClick(level: string) {
  emit('level-click', level)
  // 点击层级时清除选中条目
  selectedItemId.value = null
  selectedLevel.value = null
}

function handleItemClick(level: string, itemId: string) {
  emit('item-click', level, itemId)
  if (selectedItemId.value === itemId && selectedLevel.value === level) {
    selectedItemId.value = null
    selectedLevel.value = null
  } else {
    selectedItemId.value = itemId
    selectedLevel.value = level
  }
}

function closeDetail() {
  selectedItemId.value = null
  selectedLevel.value = null
}
</script>

<template>
  <div class="memory-layer">
    <div class="memory-header">
      <span class="memory-icon">🧠</span>
      <span class="memory-title">四级记忆系统</span>
      <span class="memory-badge">{{ levels.reduce((s, l) => s + l.items.length, 0) }} 条记忆</span>
    </div>

    <!-- 记忆金字塔 -->
    <div class="memory-pyramid">
      <div
        v-for="(level, idx) in levels"
        :key="level.level"
        class="memory-tier"
        :class="{ 'is-active': activeLevel === level.level }"
        :style="{
          '--tier-color': level.color,
          '--tier-width': `${100 - idx * 12}%`,
        }"
        @click="handleLevelClick(level.level)"
      >
        <!-- 层级主体 -->
        <div class="tier-body">
          <div class="tier-icon">{{ level.icon }}</div>
          <div class="tier-info">
            <div class="tier-name">
              <span class="tier-level">L{{ 4 - idx }}</span>
              {{ level.name }}
            </div>
            <div class="tier-subtitle">{{ level.subtitle }}</div>
          </div>
          <div class="tier-stats">
            <span class="stat-count">{{ level.items.length }}</span>
            <span class="stat-label">条</span>
          </div>
        </div>

        <!-- 记忆条目（展开时显示） -->
        <div
          v-if="level.expanded && level.items.length > 0"
          class="tier-items"
        >
          <div
            v-for="item in level.items.slice(0, 5)"
            :key="item.id"
            class="memory-item"
            :class="{ selected: selectedItemId === item.id && selectedLevel === level.level }"
            @click.stop="handleItemClick(level.level, item.id)"
          >
            <span class="item-type">{{ item.type }}</span>
            <span class="item-title">{{ item.title }}</span>
            <span class="item-arrow">›</span>
            <div
              v-if="item.importance"
              class="item-importance"
              :style="{ width: item.importance + '%' }"
            ></div>
          </div>
          <div v-if="level.items.length > 5" class="item-more">
            +{{ level.items.length - 5 }} 更多
          </div>
        </div>

        <!-- 元信息 -->
        <div class="tier-meta">
          <span class="meta-item">
            <span class="meta-icon">📦</span>
            {{ level.capacity }}
          </span>
          <span class="meta-item">
            <span class="meta-icon">⏱️</span>
            {{ level.retention }}
          </span>
        </div>
      </div>
    </div>

    <!-- 沉淀方向指示 -->
    <div class="memory-flow-indicator">
      <div class="flow-arrow">↓</div>
      <span class="flow-text">记忆沉淀方向</span>
      <div class="flow-arrow">↓</div>
    </div>

    <!-- 记忆条目详情卡片 -->
    <transition name="detail-slide">
      <div v-if="selectedItem" class="memory-detail-card">
        <div class="detail-card-header">
          <span class="detail-card-type">{{ selectedItem.type }}</span>
          <button class="detail-card-close" @click="closeDetail">✕</button>
        </div>
        <div class="detail-card-title">{{ selectedItem.title }}</div>
        <div v-if="selectedItem.description" class="detail-card-desc">
          {{ selectedItem.description }}
        </div>
        <div v-if="selectedItem.tags && selectedItem.tags.length > 0" class="detail-card-tags">
          <span v-for="tag in selectedItem.tags" :key="tag" class="detail-tag">{{ tag }}</span>
        </div>
        <div class="detail-card-footer">
          <div class="importance-bar">
            <span class="importance-label">重要程度</span>
            <div class="importance-track">
              <div
                class="importance-fill"
                :style="{ width: (selectedItem.importance ?? 50) + '%' }"
              ></div>
            </div>
            <span class="importance-value">{{ selectedItem.importance ?? 50 }}%</span>
          </div>
        </div>
      </div>
    </transition>
  </div>
</template>

<style scoped>
.memory-layer {
  background: linear-gradient(180deg, #0c1222 0%, #1a1f3a 100%);
  border: 1px solid rgba(139, 92, 246, 0.15);
  border-radius: 12px;
  padding: 14px;
  position: relative;
}

.memory-header {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 14px;
}

.memory-icon {
  font-size: 16px;
}

.memory-title {
  font-size: 13px;
  font-weight: 600;
  color: #e2e8f0;
}

.memory-badge {
  margin-left: auto;
  font-size: 10px;
  padding: 2px 8px;
  background: rgba(139, 92, 246, 0.15);
  color: #c4b5fd;
  border-radius: 10px;
  border: 1px solid rgba(139, 92, 246, 0.3);
}

/* 记忆金字塔 */
.memory-pyramid {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.memory-tier {
  position: relative;
  background: rgba(255, 255, 255, 0.03);
  border: 1px solid rgba(255, 255, 255, 0.06);
  border-left: 3px solid var(--tier-color);
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.3s ease;
  overflow: hidden;
}

.memory-tier:hover {
  background: rgba(255, 255, 255, 0.06);
  transform: translateX(2px);
}

.memory-tier.is-active {
  border-color: var(--tier-color);
  background: rgba(255, 255, 255, 0.05);
}

.tier-body {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px 12px;
}

.tier-icon {
  font-size: 18px;
  width: 32px;
  height: 32px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(255, 255, 255, 0.05);
  border-radius: 8px;
  flex-shrink: 0;
}

.tier-info {
  flex: 1;
  min-width: 0;
}

.tier-name {
  font-size: 12px;
  font-weight: 600;
  color: #e2e8f0;
  display: flex;
  align-items: center;
  gap: 6px;
}

.tier-level {
  font-size: 9px;
  font-weight: 700;
  color: var(--tier-color);
  background: color-mix(in srgb, var(--tier-color) 20%, transparent);
  padding: 1px 5px;
  border-radius: 4px;
  letter-spacing: 0.5px;
}

.tier-subtitle {
  font-size: 10px;
  color: #64748b;
  margin-top: 2px;
}

.tier-stats {
  text-align: right;
  flex-shrink: 0;
}

.stat-count {
  font-size: 16px;
  font-weight: 700;
  color: var(--tier-color);
  display: block;
  line-height: 1;
}

.stat-label {
  font-size: 9px;
  color: #64748b;
}

/* 记忆条目 */
.tier-items {
  padding: 0 12px 10px;
  border-top: 1px solid rgba(255, 255, 255, 0.05);
  margin-top: -2px;
  padding-top: 8px;
}

.memory-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 5px 8px;
  border-radius: 6px;
  font-size: 11px;
  transition: background 0.2s ease;
  position: relative;
}

.memory-item:hover {
  background: rgba(255, 255, 255, 0.05);
}

.item-type {
  font-size: 9px;
  padding: 1px 5px;
  background: rgba(255, 255, 255, 0.08);
  color: #94a3b8;
  border-radius: 4px;
  flex-shrink: 0;
}

.item-title {
  flex: 1;
  color: #cbd5e1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.item-importance {
  position: absolute;
  bottom: 0;
  left: 0;
  height: 2px;
  background: linear-gradient(90deg, var(--tier-color), transparent);
  border-radius: 0 0 6px 6px;
}

.item-more {
  font-size: 10px;
  color: #64748b;
  text-align: center;
  padding: 4px;
  cursor: pointer;
}

.item-more:hover {
  color: #94a3b8;
}

/* 元信息 */
.tier-meta {
  display: flex;
  gap: 12px;
  padding: 6px 12px;
  background: rgba(0, 0, 0, 0.2);
  border-top: 1px solid rgba(255, 255, 255, 0.04);
}

.meta-item {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 10px;
  color: #64748b;
}

.meta-icon {
  font-size: 10px;
}

/* 流向指示 */
.memory-flow-indicator {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  margin-top: 12px;
  padding-top: 10px;
  border-top: 1px dashed rgba(255, 255, 255, 0.08);
}

.flow-arrow {
  color: #6366f1;
  font-size: 12px;
  animation: flow-bounce 2s ease-in-out infinite;
}

.flow-arrow:last-child {
  animation-delay: 0.5s;
}

@keyframes flow-bounce {
  0%, 100% { transform: translateY(0); opacity: 0.5; }
  50% { transform: translateY(3px); opacity: 1; }
}

.flow-text {
  font-size: 10px;
  color: #64748b;
  letter-spacing: 1px;
}

/* 条目选中态 */
.memory-item.selected {
  background: rgba(139, 92, 246, 0.15) !important;
  border-left: 2px solid #8b5cf6;
}

.item-arrow {
  margin-left: auto;
  font-size: 12px;
  color: #64748b;
  transition: transform 0.2s ease;
}

.memory-item.selected .item-arrow {
  color: #c4b5fd;
  transform: rotate(90deg);
}

/* 记忆详情卡片 */
.memory-detail-card {
  margin-top: 12px;
  background: linear-gradient(135deg, rgba(139, 92, 246, 0.1) 0%, rgba(99, 102, 241, 0.05) 100%);
  border: 1px solid rgba(139, 92, 246, 0.3);
  border-radius: 10px;
  padding: 12px;
}

.detail-slide-enter-active,
.detail-slide-leave-active {
  transition: all 0.3s ease;
  max-height: 300px;
  opacity: 1;
  transform: translateY(0);
}

.detail-slide-enter-from,
.detail-slide-leave-to {
  max-height: 0;
  opacity: 0;
  transform: translateY(-10px);
  margin-top: 0;
  padding-top: 0;
  padding-bottom: 0;
}

.detail-card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 8px;
}

.detail-card-type {
  font-size: 10px;
  padding: 2px 8px;
  background: rgba(139, 92, 246, 0.2);
  color: #c4b5fd;
  border-radius: 4px;
  font-weight: 500;
}

.detail-card-close {
  width: 20px;
  height: 20px;
  border: none;
  background: rgba(255, 255, 255, 0.05);
  color: #64748b;
  border-radius: 4px;
  cursor: pointer;
  font-size: 10px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.detail-card-close:hover {
  background: rgba(255, 255, 255, 0.1);
  color: #e2e8f0;
}

.detail-card-title {
  font-size: 13px;
  font-weight: 600;
  color: #e2e8f0;
  margin-bottom: 8px;
}

.detail-card-desc {
  font-size: 11px;
  color: #94a3b8;
  line-height: 1.6;
  margin-bottom: 10px;
  padding: 8px 10px;
  background: rgba(0, 0, 0, 0.2);
  border-radius: 6px;
}

.detail-card-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 5px;
  margin-bottom: 10px;
}

.detail-tag {
  font-size: 9px;
  padding: 2px 6px;
  background: rgba(255, 255, 255, 0.06);
  color: #94a3b8;
  border-radius: 4px;
}

.detail-card-footer {
  padding-top: 8px;
  border-top: 1px solid rgba(255, 255, 255, 0.06);
}

.importance-bar {
  display: flex;
  align-items: center;
  gap: 8px;
}

.importance-label {
  font-size: 10px;
  color: #94a3b8;
  flex-shrink: 0;
  width: 50px;
}

.importance-track {
  flex: 1;
  height: 4px;
  background: rgba(255, 255, 255, 0.08);
  border-radius: 2px;
  overflow: hidden;
}

.importance-fill {
  height: 100%;
  background: linear-gradient(90deg, #8b5cf6, #a855f7);
  border-radius: 2px;
  transition: width 0.3s ease;
}

.importance-value {
  font-size: 10px;
  color: #c4b5fd;
  font-weight: 600;
  width: 30px;
  text-align: right;
}
</style>
