<!-- Generated by Trae Work -->
<script setup lang="ts">
import { ref, computed } from 'vue'

export interface VersionNode {
  id: string
  version_no: string
  label?: string
  word_count: number
  created_at: string
  is_current: boolean
  is_favorite: boolean
  summary?: string
  rating?: number
  template_used?: string
  generation_time_ms?: number
  agent_used?: string
  diff_prev?: string
  highlights?: string[]
}

const props = defineProps<{
  versions: VersionNode[]
  currentVersionId?: string
}>()

const emit = defineEmits<{
  (e: 'select', versionId: string): void
  (e: 'compare', versionId: string): void
}>()

const expandedId = ref<string | null>(null)

const expandedVersion = computed(() =>
  expandedId.value ? props.versions.find(v => v.id === expandedId.value) : null
)

function toggleExpand(versionId: string) {
  if (expandedId.value === versionId) {
    expandedId.value = null
  } else {
    expandedId.value = versionId
  }
}

function handleVersionClick(version: VersionNode) {
  toggleExpand(version.id)
}

function formatDate(dateStr: string): string {
  const d = new Date(dateStr)
  const now = new Date()
  const diffMs = now.getTime() - d.getTime()
  const diffMins = Math.floor(diffMs / 60000)
  if (diffMins < 1) return '刚刚'
  if (diffMins < 60) return `${diffMins} 分钟前`
  const diffHours = Math.floor(diffMins / 60)
  if (diffHours < 24) return `${diffHours} 小时前`
  return `${d.getMonth() + 1}/${d.getDate()} ${d.getHours()}:${d.getMinutes().toString().padStart(2, '0')}`
}

function formatFullDate(dateStr: string): string {
  const d = new Date(dateStr)
  return `${d.getFullYear()}-${(d.getMonth()+1).toString().padStart(2,'0')}-${d.getDate().toString().padStart(2,'0')} ${d.getHours()}:${d.getMinutes().toString().padStart(2,'0')}`
}

function formatDuration(ms?: number): string {
  if (!ms) return '—'
  const s = Math.floor(ms / 1000)
  if (s < 60) return `${s} 秒`
  const m = Math.floor(s / 60)
  return `${m} 分 ${s % 60} 秒`
}

function formatWords(count: number): string {
  if (count >= 10000) return `${(count / 10000).toFixed(1)}万`
  if (count >= 1000) return `${(count / 1000).toFixed(1)}k`
  return count.toString()
}
</script>

<template>
  <div class="version-timeline">
    <div class="timeline-header">
      <span class="timeline-icon">📜</span>
      <span class="timeline-title">生成版本</span>
      <span class="timeline-count">{{ versions.length }} 个版本</span>
    </div>

    <!-- 时间线 -->
    <div class="timeline-track">
      <!-- 垂直连接线 -->
      <div class="timeline-line"></div>

      <!-- 版本节点 -->
      <div
        v-for="(v, idx) in versions"
        :key="v.id"
        class="version-node"
        :class="{
          'is-current': v.is_current,
          'is-favorite': v.is_favorite,
          'is-expanded': expandedId === v.id,
        }"
        @click="handleVersionClick(v)"
      >
        <!-- 节点圆点 -->
        <div class="node-dot">
          <span v-if="v.is_current" class="dot-inner"></span>
          <span v-else-if="v.is_favorite" class="dot-star">⭐</span>
        </div>

        <!-- 版本卡片 -->
        <div class="version-card">
          <div class="card-header">
            <span class="version-no">{{ v.version_no }}</span>
            <div class="card-header-right">
              <span v-if="v.is_current" class="version-badge current">当前</span>
              <span v-else-if="v.is_favorite" class="version-badge favorite">收藏</span>
              <span class="expand-arrow" :class="{ expanded: expandedId === v.id }">▾</span>
            </div>
          </div>

          <div v-if="v.summary" class="version-summary">{{ v.summary }}</div>

          <div class="card-footer">
            <span class="version-words">{{ formatWords(v.word_count) }} 字</span>
            <span class="version-time">{{ formatDate(v.created_at) }}</span>
          </div>

          <div v-if="v.rating" class="version-rating">
            <span v-for="i in 5" :key="i" class="star" :class="{ filled: i <= (v.rating || 0) }">★</span>
          </div>

          <!-- 展开详情 -->
          <transition name="version-detail">
            <div v-if="expandedId === v.id" class="version-detail">
              <div class="detail-grid">
                <div class="detail-item">
                  <span class="detail-item-label">生成时间</span>
                  <span class="detail-item-value">{{ formatFullDate(v.created_at) }}</span>
                </div>
                <div class="detail-item">
                  <span class="detail-item-label">生成耗时</span>
                  <span class="detail-item-value">{{ formatDuration(v.generation_time_ms) }}</span>
                </div>
                <div class="detail-item">
                  <span class="detail-item-label">使用模板</span>
                  <span class="detail-item-value">{{ v.template_used || '默认' }}</span>
                </div>
                <div class="detail-item">
                  <span class="detail-item-label">字数</span>
                  <span class="detail-item-value">{{ v.word_count.toLocaleString() }} 字</span>
                </div>
              </div>

              <div v-if="v.highlights && v.highlights.length > 0" class="detail-highlights">
                <div class="detail-highlights-title">✨ 版本亮点</div>
                <div class="highlight-tags">
                  <span v-for="(h, i) in v.highlights" :key="i" class="highlight-tag">{{ h }}</span>
                </div>
              </div>

              <div class="detail-actions">
                <button
                  v-if="!v.is_current"
                  class="detail-action-btn primary"
                  @click.stop="emit('select', v.id)"
                >
                  🔄 切换到此版本
                </button>
                <button
                  class="detail-action-btn"
                  @click.stop="emit('compare', v.id)"
                >
                  📊 对比差异
                </button>
              </div>
            </div>
          </transition>

          <div class="card-actions">
            <button
              v-if="!v.is_current"
              class="action-btn switch-btn"
              @click.stop="emit('select', v.id)"
            >
              切换到此版本
            </button>
            <button
              class="action-btn compare-btn"
              @click.stop="emit('compare', v.id)"
            >
              对比
            </button>
          </div>
        </div>
      </div>

      <!-- 空状态 -->
      <div v-if="versions.length === 0" class="timeline-empty">
        <div class="empty-illustration">
          <div class="empty-node-line">
            <span class="empty-dot"></span>
            <span class="empty-dot ghost"></span>
            <span class="empty-dot ghost"></span>
          </div>
        </div>
        <span class="empty-icon">📜</span>
        <span class="empty-text">暂无版本记录</span>
        <span class="empty-hint">生成章节后自动创建版本</span>
        <div class="empty-features">
          <div class="feature-item">
            <span class="feature-icon">🔄</span>
            <span>版本回退</span>
          </div>
          <div class="feature-item">
            <span class="feature-icon">📊</span>
            <span>差异对比</span>
          </div>
          <div class="feature-item">
            <span class="feature-icon">⭐</span>
            <span>收藏标记</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.version-timeline {
  background: linear-gradient(180deg, #0f172a 0%, #1e293b 100%);
  border: 1px solid rgba(59, 130, 246, 0.15);
  border-radius: 12px;
  padding: 14px;
}

.timeline-header {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 16px;
}

.timeline-icon {
  font-size: 16px;
}

.timeline-title {
  font-size: 13px;
  font-weight: 600;
  color: #e2e8f0;
}

.timeline-count {
  margin-left: auto;
  font-size: 10px;
  padding: 2px 8px;
  background: rgba(59, 130, 246, 0.15);
  color: #93c5fd;
  border-radius: 10px;
  border: 1px solid rgba(59, 130, 246, 0.3);
}

/* 时间线轨道 */
.timeline-track {
  position: relative;
  padding-left: 20px;
  max-height: 400px;
  overflow-y: auto;
}

.timeline-line {
  position: absolute;
  left: 7px;
  top: 4px;
  bottom: 4px;
  width: 2px;
  background: linear-gradient(180deg, #3b82f6, #6366f1, #8b5cf6);
  border-radius: 1px;
}

/* 版本节点 */
.version-node {
  position: relative;
  margin-bottom: 14px;
  cursor: pointer;
}

.node-dot {
  position: absolute;
  left: -16px;
  top: 12px;
  width: 12px;
  height: 12px;
  background: #334155;
  border: 2px solid #475569;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1;
  transition: all 0.3s ease;
}

.dot-inner {
  width: 6px;
  height: 6px;
  background: #3b82f6;
  border-radius: 50%;
  box-shadow: 0 0 6px #3b82f6;
}

.dot-star {
  font-size: 8px;
}

.version-node.is-current .node-dot {
  background: #3b82f6;
  border-color: #60a5fa;
  box-shadow: 0 0 10px rgba(59, 130, 246, 0.5);
}

/* 版本卡片 */
.version-card {
  background: rgba(30, 41, 59, 0.6);
  border: 1px solid rgba(255, 255, 255, 0.06);
  border-radius: 8px;
  padding: 10px 12px;
  transition: all 0.3s ease;
}

.version-node:hover .version-card {
  border-color: rgba(59, 130, 246, 0.4);
  background: rgba(30, 41, 59, 0.9);
}

.version-node.is-current .version-card {
  border-color: rgba(59, 130, 246, 0.6);
  background: rgba(30, 58, 138, 0.3);
  box-shadow: 0 4px 12px rgba(59, 130, 246, 0.15);
}

.card-header {
  display: flex;
  align-items: center;
  gap: 6px;
  margin-bottom: 6px;
  flex-wrap: wrap;
}

.version-no {
  font-size: 13px;
  font-weight: 700;
  color: #e2e8f0;
}

.version-badge {
  font-size: 9px;
  padding: 1px 6px;
  border-radius: 4px;
  font-weight: 600;
}

.version-badge.current {
  background: rgba(59, 130, 246, 0.25);
  color: #60a5fa;
  border: 1px solid rgba(59, 130, 246, 0.4);
}

.version-badge.favorite {
  background: rgba(234, 179, 8, 0.2);
  color: #fbbf24;
  border: 1px solid rgba(234, 179, 8, 0.3);
}

.version-template {
  font-size: 9px;
  padding: 1px 5px;
  background: rgba(255, 255, 255, 0.06);
  color: #94a3b8;
  border-radius: 4px;
  margin-left: auto;
}

.version-summary {
  font-size: 11px;
  color: #94a3b8;
  line-height: 1.5;
  margin-bottom: 8px;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.card-footer {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-bottom: 6px;
}

.version-words {
  font-size: 10px;
  color: #64748b;
}

.version-time {
  font-size: 10px;
  color: #64748b;
  margin-left: auto;
}

.version-rating {
  margin-bottom: 8px;
}

.star {
  font-size: 11px;
  color: #334155;
}

.star.filled {
  color: #fbbf24;
}

.card-actions {
  display: flex;
  gap: 6px;
  padding-top: 8px;
  border-top: 1px solid rgba(255, 255, 255, 0.06);
}

.action-btn {
  flex: 1;
  font-size: 10px;
  padding: 4px 8px;
  border: 1px solid rgba(255, 255, 255, 0.1);
  background: rgba(255, 255, 255, 0.04);
  color: #94a3b8;
  border-radius: 5px;
  cursor: pointer;
  transition: all 0.2s ease;
}

.action-btn:hover {
  background: rgba(255, 255, 255, 0.08);
  color: #cbd5e1;
}

.switch-btn {
  border-color: rgba(59, 130, 246, 0.3);
  color: #60a5fa;
}

.switch-btn:hover {
  background: rgba(59, 130, 246, 0.15);
  border-color: #3b82f6;
}

/* 空状态 */
.timeline-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 30px 0;
  gap: 6px;
}

.empty-icon {
  font-size: 28px;
  opacity: 0.5;
}

.empty-text {
  font-size: 12px;
  color: #64748b;
}

.empty-hint {
  font-size: 10px;
  color: #475569;
}

.empty-illustration {
  margin-bottom: 8px;
}

.empty-node-line {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 12px;
  position: relative;
}

.empty-node-line::before {
  content: '';
  position: absolute;
  left: 20%;
  right: 20%;
  top: 50%;
  height: 2px;
  background: rgba(59, 130, 246, 0.2);
  transform: translateY(-50%);
}

.empty-dot {
  width: 14px;
  height: 14px;
  background: #3b82f6;
  border-radius: 50%;
  border: 2px solid #60a5fa;
  position: relative;
  z-index: 1;
  box-shadow: 0 0 8px rgba(59, 130, 246, 0.4);
}

.empty-dot.ghost {
  background: transparent;
  border-color: rgba(59, 130, 246, 0.3);
  box-shadow: none;
}

.empty-features {
  display: flex;
  gap: 8px;
  margin-top: 10px;
  padding-top: 10px;
  border-top: 1px dashed rgba(255, 255, 255, 0.06);
}

.feature-item {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4px;
  font-size: 9px;
  color: #64748b;
}

.feature-icon {
  font-size: 14px;
}

/* 展开箭头 */
.card-header-right {
  display: flex;
  align-items: center;
  gap: 5px;
  margin-left: auto;
}

.expand-arrow {
  font-size: 10px;
  color: #64748b;
  transition: transform 0.3s ease;
  margin-left: 2px;
}

.expand-arrow.expanded {
  transform: rotate(180deg);
  color: #60a5fa;
}

/* 展开态卡片 */
.version-node.is-expanded .version-card {
  border-color: rgba(59, 130, 246, 0.6);
  box-shadow: 0 4px 16px rgba(59, 130, 246, 0.2);
}

.version-node.is-expanded .node-dot {
  transform: scale(1.2);
}

/* 版本详情 */
.version-detail {
  margin-top: 10px;
  padding-top: 10px;
  border-top: 1px solid rgba(255, 255, 255, 0.08);
}

.version-detail-enter-active,
.version-detail-leave-active {
  transition: all 0.3s ease;
  max-height: 400px;
  opacity: 1;
  overflow: hidden;
}

.version-detail-enter-from,
.version-detail-leave-to {
  max-height: 0;
  opacity: 0;
  margin-top: 0;
  padding-top: 0;
}

.detail-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 8px;
  margin-bottom: 10px;
}

.detail-item {
  background: rgba(255, 255, 255, 0.03);
  border-radius: 6px;
  padding: 6px 8px;
}

.detail-item-label {
  display: block;
  font-size: 9px;
  color: #64748b;
  margin-bottom: 2px;
}

.detail-item-value {
  display: block;
  font-size: 11px;
  color: #cbd5e1;
  font-weight: 500;
}

.detail-highlights {
  margin-bottom: 10px;
}

.detail-highlights-title {
  font-size: 10px;
  color: #94a3b8;
  margin-bottom: 6px;
}

.highlight-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
}

.highlight-tag {
  font-size: 10px;
  padding: 3px 8px;
  background: rgba(59, 130, 246, 0.15);
  color: #93c5fd;
  border-radius: 4px;
  border: 1px solid rgba(59, 130, 246, 0.3);
}

.detail-actions {
  display: flex;
  gap: 6px;
  margin-bottom: 8px;
}

.detail-action-btn {
  flex: 1;
  font-size: 10px;
  padding: 6px 8px;
  border: 1px solid rgba(255, 255, 255, 0.1);
  background: rgba(255, 255, 255, 0.04);
  color: #94a3b8;
  border-radius: 6px;
  cursor: pointer;
  transition: all 0.2s ease;
}

.detail-action-btn:hover {
  background: rgba(255, 255, 255, 0.08);
  color: #cbd5e1;
}

.detail-action-btn.primary {
  background: rgba(59, 130, 246, 0.2);
  border-color: rgba(59, 130, 246, 0.5);
  color: #60a5fa;
}

.detail-action-btn.primary:hover {
  background: rgba(59, 130, 246, 0.3);
  border-color: #3b82f6;
}
</style>
