<!-- Generated by Trae Work -->
<script setup lang="ts">
import { ref, computed } from 'vue'

export interface PipelineStep {
  id: string
  label: string
  icon: string
  description: string
  status: 'pending' | 'running' | 'completed' | 'failed' | 'active'
  durationMs?: number
  agentName?: string
  skillCount?: number
  canRestart?: boolean
  output?: {
    summary?: string
    wordCount?: number
    highlights?: string[]
    raw?: string
  }
  error?: string
}

const props = defineProps<{
  steps: PipelineStep[]
  activeStepId?: string | null
  templateName?: string
  templateLabel?: string
  expandedStepId?: string | null
}>()

const emit = defineEmits<{
  (e: 'step-click', stepId: string): void
  (e: 'restart', stepId: string): void
  (e: 'expand', stepId: string | null): void
}>()

const localExpanded = ref<string | null>(null)

const expandedId = computed(() => props.expandedStepId ?? localExpanded.value)

function toggleExpand(stepId: string) {
  if (expandedId.value === stepId) {
    localExpanded.value = null
    emit('expand', null)
  } else {
    localExpanded.value = stepId
    emit('expand', stepId)
  }
}

const statusMap: Record<string, { class: string; dot: string }> = {
  pending:   { class: 'step-pending',   dot: '○' },
  running:   { class: 'step-running',   dot: '' },
  completed: { class: 'step-completed', dot: '✓' },
  failed:    { class: 'step-failed',    dot: '✕' },
  active:    { class: 'step-active',    dot: '▶' },
}

const completedCount = computed(() =>
  props.steps.filter(s => s.status === 'completed').length
)

const progressPercent = computed(() =>
  props.steps.length > 0 ? (completedCount.value / props.steps.length) * 100 : 0
)

const expandedStep = computed(() =>
  expandedId.value ? props.steps.find(s => s.id === expandedId.value) : null
)

function formatDuration(ms?: number): string {
  if (!ms) return ''
  const s = Math.floor(ms / 1000)
  if (s < 60) return `${s}s`
  const m = Math.floor(s / 60)
  return `${m}m${(s % 60).toString().padStart(2, '0')}s`
}

function handleClick(step: PipelineStep) {
  emit('step-click', step.id)
  // 已完成的步骤可以展开查看产物
  if (step.status === 'completed' || step.status === 'failed') {
    toggleExpand(step.id)
  }
}

function handleRestart(e: Event, stepId: string) {
  e.stopPropagation()
  emit('restart', stepId)
}
</script>

<template>
  <div class="workflow-pipeline">
    <!-- 流水线头部 -->
    <div class="pipeline-header">
      <div class="pipeline-title">
        <span class="pipeline-icon">⚙️</span>
        <span class="pipeline-name">{{ templateLabel || '工作流' }}</span>
        <span class="pipeline-badge">{{ steps.length }} 步流水线</span>
      </div>
      <div class="pipeline-progress">
        <div class="progress-bar">
          <div class="progress-fill" :style="{ width: progressPercent + '%' }"></div>
        </div>
        <span class="progress-text">{{ completedCount }}/{{ steps.length }} 完成</span>
      </div>
    </div>

    <!-- 流水线主体 - 横向步骤流 -->
    <div class="pipeline-track">
      <!-- 连接线背景 -->
      <div class="track-connector">
        <div class="connector-line"></div>
        <div
          class="connector-fill"
          :style="{ width: `calc(${progressPercent}% - 24px)` }"
        ></div>
      </div>

      <!-- 步骤节点 -->
      <div
        v-for="(step, idx) in steps"
        :key="step.id"
        class="pipeline-step"
        :class="[
          statusMap[step.status].class,
          { 'is-active': step.id === activeStepId || step.status === 'active' }
        ]"
        @click="handleClick(step)"
      >
        <!-- 步骤圆形节点 -->
        <div class="step-node">
          <div v-if="step.status === 'running'" class="node-pulse">
            <span></span><span></span><span></span>
          </div>
          <span class="node-icon">{{ statusMap[step.status].dot || step.icon }}</span>
          <span class="step-index">{{ idx + 1 }}</span>
        </div>

        <!-- 步骤内容卡片 -->
        <div class="step-card">
          <div class="step-card-header">
            <span class="step-label">{{ step.label }}</span>
            <span class="step-actions-wrap">
              <span v-if="step.durationMs" class="step-duration">
                {{ formatDuration(step.durationMs) }}
              </span>
              <span
                v-if="step.status === 'completed' || step.status === 'failed'"
                class="step-expand-arrow"
                :class="{ expanded: expandedId === step.id }"
              >▾</span>
            </span>
          </div>
          <div class="step-desc">{{ step.description }}</div>
          <div v-if="step.agentName" class="step-agent">
            <span class="agent-dot"></span>
            <span class="agent-name">{{ step.agentName }}</span>
            <span v-if="step.skillCount" class="skill-count">{{ step.skillCount }} 技能</span>
          </div>
          <div
            v-if="step.status === 'completed' && step.canRestart !== false"
            class="step-actions"
          >
            <button class="restart-btn" @click="handleRestart($event, step.id)">
              🔄 从这里重跑
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- 步骤产物详情面板 -->
    <transition name="detail-expand">
      <div v-if="expandedStep" class="step-detail-panel">
        <div class="detail-header">
          <div class="detail-title">
            <span class="detail-icon">{{ expandedStep.icon }}</span>
            <span>{{ expandedStep.label }} — 步骤产物</span>
          </div>
          <button class="detail-close" @click="toggleExpand(expandedStep.id)">✕</button>
        </div>
        <div class="detail-body">
          <!-- 错误信息 -->
          <div v-if="expandedStep.status === 'failed' && expandedStep.error" class="detail-error">
            <span class="error-icon">⚠️</span>
            <span class="error-text">{{ expandedStep.error }}</span>
          </div>

          <!-- 成功状态的产物 -->
          <template v-else-if="expandedStep.output">
            <!-- 摘要 -->
            <div v-if="expandedStep.output.summary" class="detail-section">
              <div class="detail-label">📝 产出摘要</div>
              <div class="detail-summary">{{ expandedStep.output.summary }}</div>
            </div>

            <!-- 字数 -->
            <div v-if="expandedStep.output.wordCount" class="detail-metrics">
              <div class="metric">
                <span class="metric-value">{{ expandedStep.output.wordCount.toLocaleString() }}</span>
                <span class="metric-label">字</span>
              </div>
              <div class="metric">
                <span class="metric-value">{{ formatDuration(expandedStep.durationMs) }}</span>
                <span class="metric-label">耗时</span>
              </div>
              <div class="metric">
                <span class="metric-value">{{ expandedStep.agentName }}</span>
                <span class="metric-label">执行 Agent</span>
              </div>
            </div>

            <!-- 亮点 -->
            <div v-if="expandedStep.output.highlights && expandedStep.output.highlights.length > 0" class="detail-section">
              <div class="detail-label">✨ 关键产出</div>
              <div class="highlights-list">
                <div v-for="(h, i) in expandedStep.output.highlights" :key="i" class="highlight-item">
                  <span class="highlight-dot"></span>
                  <span>{{ h }}</span>
                </div>
              </div>
            </div>
          </template>

          <!-- 无产物 -->
          <div v-else class="detail-empty">
            <span class="empty-icon">📭</span>
            <span>暂无产出详情</span>
          </div>
        </div>
      </div>
    </transition>
  </div>
</template>

<style scoped>
.workflow-pipeline {
  background: linear-gradient(180deg, #0f172a 0%, #1e293b 100%);
  border: 1px solid rgba(99, 102, 241, 0.2);
  border-radius: 12px;
  padding: 16px 20px 24px;
  position: relative;
  overflow: hidden;
}

.workflow-pipeline::before {
  content: '';
  position: absolute;
  top: 0; left: 0; right: 0;
  height: 2px;
  background: linear-gradient(90deg, #6366f1, #8b5cf6, #a855f7, #8b5cf6, #6366f1);
  background-size: 200% 100%;
  animation: shimmer 3s linear infinite;
}

@keyframes shimmer {
  0% { background-position: 200% 0; }
  100% { background-position: -200% 0; }
}

/* 头部 */
.pipeline-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 20px;
}

.pipeline-title {
  display: flex;
  align-items: center;
  gap: 10px;
}

.pipeline-icon {
  font-size: 18px;
}

.pipeline-name {
  font-size: 15px;
  font-weight: 600;
  color: #e2e8f0;
  letter-spacing: 0.3px;
}

.pipeline-badge {
  font-size: 11px;
  padding: 2px 8px;
  background: rgba(99, 102, 241, 0.15);
  color: #a5b4fc;
  border-radius: 10px;
  border: 1px solid rgba(99, 102, 241, 0.3);
}

.pipeline-progress {
  display: flex;
  align-items: center;
  gap: 10px;
}

.progress-bar {
  width: 120px;
  height: 4px;
  background: rgba(255, 255, 255, 0.1);
  border-radius: 2px;
  overflow: hidden;
}

.progress-fill {
  height: 100%;
  background: linear-gradient(90deg, #6366f1, #a855f7);
  border-radius: 2px;
  transition: width 0.5s ease;
}

.progress-text {
  font-size: 12px;
  color: #94a3b8;
  min-width: 60px;
}

/* 流水线轨道 */
.pipeline-track {
  position: relative;
  display: flex;
  justify-content: space-between;
  padding: 20px 8px 0;
  min-height: 140px;
}

/* 连接线 */
.track-connector {
  position: absolute;
  top: 38px;
  left: 40px;
  right: 40px;
  height: 2px;
  z-index: 0;
}

.connector-line {
  position: absolute;
  inset: 0;
  background: rgba(255, 255, 255, 0.08);
  border-radius: 1px;
}

.connector-fill {
  position: absolute;
  left: 0;
  top: 0;
  height: 100%;
  background: linear-gradient(90deg, #6366f1, #a855f7);
  border-radius: 1px;
  transition: width 0.5s ease;
}

/* 步骤节点 */
.pipeline-step {
  position: relative;
  z-index: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  cursor: pointer;
  flex: 1;
  max-width: 160px;
  transition: transform 0.2s ease;
}

.pipeline-step:hover {
  transform: translateY(-2px);
}

/* 圆形节点 */
.step-node {
  width: 36px;
  height: 36px;
  border-radius: 50%;
  background: #1e293b;
  border: 2px solid rgba(255, 255, 255, 0.15);
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
  margin-bottom: 10px;
  font-size: 14px;
  color: #64748b;
  transition: all 0.3s ease;
  flex-shrink: 0;
}

.step-index {
  position: absolute;
  bottom: -6px;
  right: -6px;
  width: 16px;
  height: 16px;
  background: #334155;
  color: #94a3b8;
  font-size: 9px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 600;
  border: 2px solid #0f172a;
}

/* 脉冲动画 */
.node-pulse {
  position: absolute;
  inset: -4px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
}

.node-pulse span {
  position: absolute;
  width: 100%;
  height: 100%;
  border-radius: 50%;
  border: 2px solid #6366f1;
  opacity: 0;
  animation: pulse-ring 1.5s ease-out infinite;
}

.node-pulse span:nth-child(2) { animation-delay: 0.5s; }
.node-pulse span:nth-child(3) { animation-delay: 1s; }

@keyframes pulse-ring {
  0% { transform: scale(0.8); opacity: 0.8; }
  100% { transform: scale(1.6); opacity: 0; }
}

/* 步骤卡片 */
.step-card {
  background: rgba(30, 41, 59, 0.7);
  border: 1px solid rgba(255, 255, 255, 0.06);
  border-radius: 8px;
  padding: 10px 12px;
  width: 100%;
  backdrop-filter: blur(8px);
  transition: all 0.3s ease;
}

.pipeline-step:hover .step-card {
  border-color: rgba(99, 102, 241, 0.4);
  background: rgba(30, 41, 59, 0.9);
}

.step-card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 4px;
}

.step-label {
  font-size: 13px;
  font-weight: 600;
  color: #cbd5e1;
}

.step-duration {
  font-size: 10px;
  color: #64748b;
  background: rgba(0, 0, 0, 0.2);
  padding: 1px 6px;
  border-radius: 8px;
}

.step-desc {
  font-size: 11px;
  color: #64748b;
  line-height: 1.4;
  margin-bottom: 6px;
}

.step-agent {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 10px;
  color: #94a3b8;
  margin-bottom: 4px;
}

.agent-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: #6366f1;
}

.skill-count {
  margin-left: auto;
  color: #a5b4fc;
  background: rgba(99, 102, 241, 0.15);
  padding: 1px 5px;
  border-radius: 6px;
}

.step-actions {
  margin-top: 6px;
  padding-top: 6px;
  border-top: 1px solid rgba(255, 255, 255, 0.06);
}

.restart-btn {
  width: 100%;
  font-size: 10px;
  padding: 4px 8px;
  border: 1px solid rgba(99, 102, 241, 0.4);
  color: #a5b4fc;
  background: rgba(99, 102, 241, 0.1);
  border-radius: 6px;
  cursor: pointer;
  transition: all 0.2s ease;
}

.restart-btn:hover {
  background: rgba(99, 102, 241, 0.25);
  border-color: #6366f1;
  color: #c7d2fe;
}

/* 状态样式 */
.step-completed .step-node {
  background: linear-gradient(135deg, #10b981, #059669);
  border-color: #10b981;
  color: #fff;
  box-shadow: 0 0 12px rgba(16, 185, 129, 0.3);
}

.step-completed .step-index {
  background: #10b981;
  color: #fff;
}

.step-running .step-node {
  background: linear-gradient(135deg, #6366f1, #8b5cf6);
  border-color: #6366f1;
  color: #fff;
  box-shadow: 0 0 20px rgba(99, 102, 241, 0.4);
}

.step-running .step-index {
  background: #6366f1;
  color: #fff;
}

.step-failed .step-node {
  background: linear-gradient(135deg, #ef4444, #dc2626);
  border-color: #ef4444;
  color: #fff;
}

.step-failed .step-index {
  background: #ef4444;
  color: #fff;
}

.step-active .step-node {
  background: linear-gradient(135deg, #6366f1, #a855f7);
  border-color: #a855f7;
  color: #fff;
  box-shadow: 0 0 16px rgba(168, 85, 247, 0.3);
}

.step-active .step-card {
  border-color: rgba(168, 85, 247, 0.5);
  background: rgba(30, 27, 75, 0.6);
}

.is-active .step-card {
  border-color: rgba(99, 102, 241, 0.6);
}

/* 展开箭头 */
.step-actions-wrap {
  display: flex;
  align-items: center;
  gap: 6px;
}

.step-expand-arrow {
  font-size: 10px;
  color: #64748b;
  transition: transform 0.3s ease;
}

.step-expand-arrow.expanded {
  transform: rotate(180deg);
  color: #a5b4fc;
}

/* 详情面板 */
.step-detail-panel {
  margin-top: 16px;
  background: rgba(15, 23, 42, 0.8);
  border: 1px solid rgba(99, 102, 241, 0.3);
  border-radius: 10px;
  overflow: hidden;
}

.detail-expand-enter-active,
.detail-expand-leave-active {
  transition: all 0.3s ease;
  max-height: 400px;
  opacity: 1;
}

.detail-expand-enter-from,
.detail-expand-leave-to {
  max-height: 0;
  opacity: 0;
  margin-top: 0;
}

.detail-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px 14px;
  background: rgba(99, 102, 241, 0.1);
  border-bottom: 1px solid rgba(99, 102, 241, 0.2);
}

.detail-title {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 13px;
  font-weight: 600;
  color: #e2e8f0;
}

.detail-icon {
  font-size: 16px;
}

.detail-close {
  width: 24px;
  height: 24px;
  border: none;
  background: rgba(255, 255, 255, 0.05);
  color: #64748b;
  border-radius: 6px;
  cursor: pointer;
  font-size: 11px;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.2s ease;
}

.detail-close:hover {
  background: rgba(255, 255, 255, 0.1);
  color: #e2e8f0;
}

.detail-body {
  padding: 14px;
}

.detail-section {
  margin-bottom: 12px;
}

.detail-section:last-child {
  margin-bottom: 0;
}

.detail-label {
  font-size: 11px;
  color: #94a3b8;
  margin-bottom: 6px;
  font-weight: 500;
}

.detail-summary {
  font-size: 12px;
  color: #cbd5e1;
  line-height: 1.7;
  padding: 10px 12px;
  background: rgba(255, 255, 255, 0.03);
  border-radius: 6px;
  border-left: 3px solid #6366f1;
}

.detail-metrics {
  display: flex;
  gap: 12px;
  margin-bottom: 12px;
}

.metric {
  flex: 1;
  text-align: center;
  padding: 10px;
  background: rgba(255, 255, 255, 0.03);
  border-radius: 8px;
  border: 1px solid rgba(255, 255, 255, 0.06);
}

.metric-value {
  display: block;
  font-size: 16px;
  font-weight: 700;
  color: #a5b4fc;
  margin-bottom: 2px;
}

.metric-label {
  font-size: 10px;
  color: #64748b;
}

.highlights-list {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.highlight-item {
  display: flex;
  align-items: flex-start;
  gap: 8px;
  font-size: 12px;
  color: #cbd5e1;
  padding: 6px 10px;
  background: rgba(255, 255, 255, 0.02);
  border-radius: 6px;
}

.highlight-dot {
  width: 5px;
  height: 5px;
  background: #a855f7;
  border-radius: 50%;
  margin-top: 6px;
  flex-shrink: 0;
}

.detail-error {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  padding: 12px;
  background: rgba(239, 68, 68, 0.1);
  border: 1px solid rgba(239, 68, 68, 0.3);
  border-radius: 8px;
}

.error-icon {
  font-size: 18px;
}

.error-text {
  font-size: 12px;
  color: #fca5a5;
  line-height: 1.6;
}

.detail-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 6px;
  padding: 20px;
  color: #64748b;
  font-size: 12px;
}

.empty-icon {
  font-size: 28px;
  opacity: 0.5;
}
</style>
